input {
  file {
    path => "/Users/aviralchauhan/btp/open-food-facts/server/datasets/OFF_Dataset_with_predictions.csv"
    start_position => "beginning"
    sincedb_path => "/dev/null"  # Changed from "NULL" to "/dev/null" to disable sincedb
  }
}

filter {
  csv {
    separator => ","
    columns => ["fat_100g",
      "carbohydrates_100g",
      "proteins_100g",
      "sodium_100g",
      "sugars_100g",
      "saturated-fat_100g",
      "energy-kcal_100g",
      "code",
      "url",
      "created_datetime",
      "last_updated_datetime",
      "product_name",
      "brands",
      "categories_en",
      "countries_en",
      "ingredients_text",
      "ingredients_analysis_tags",
      "additives_n",
      "nutriscore_grade",
      "nova_group",
      "pnns_groups_1",
      "pnns_groups_2",
      "food_groups_en",
      "ecoscore_grade",
      "nutrient_levels_tags",
      "completeness",
      "main_category_en",
      "nutrition-score-fr_100g",
      "predicted"]
  }
}

output {
  elasticsearch {
    hosts => ["https://1c198debd0fc466ab96f32d9b06c4b53.asia-south1.gcp.elastic-cloud.com:443"]
    index => "open-food-facts-database"
    ssl => true
    ssl_verification_mode => "none" 
    user => "elastic"
    password => "cY4UW1A1p5OcZ6nZ7yVd5gF1"
  }
  stdout { codec => rubydebug } 
}